### ISSUE TITLE
Unable to use ctr + space to bring up spotlightify

### ISSUE THREAD

**Issue by rohitnawani** [spotlightify/spotlightify#13]
As the title suggests, I get this error after following the installation step on my Mac OS and am unable to hit ctrl + space to bring up spotlightify. 

> [CACHE]	Starting
> Starting image cache thread
> [CACHE]	Initialised
> [CACHE]	Starting
> [CACHE]	Initialised
> [CACHE]	Starting
> 
>  195
> [CACHE]	Terminating
> Error occurred removing key from pressed_keys
> Error occurred removing key from pressed_keys
> Error occurred removing key from pressed_keys
> Error occurred removing key from pressed_keys
> Error occurred removing key from pressed_keys
> [CACHE]	Terminating
> Error occurred removing key from pressed_keys
> Error occurred removing key from pressed_keys

**Comment by MarkMcMoran** [comment]
Please try cloning lastest version of repo, and let us know  if it resolves issue. I've personally tested the functionality on MacOS High Sierra.

**Comment by rohitnawani** [comment]
Thanks for the new patch - all the cache works now but there is still a problem with bringing up spotlightify with `ctr + space` on my Mac OS Catalina.

> [CACHE] [MANAGER] Initialised
> [CACHE] [SONG] Initialised
> [CACHE] [IMAGE] Initialised
> [CACHE] [PLAYLIST] Initialised
> [CACHE] [LIKED] Initialised
> [CACHE] [ALBUM] Initialised
> [CACHE] [ARTIST] Initialised
> [CACHE] [SONG] Starting
> [CACHE] [IMAGE] Starting
> [CACHE] [PLAYLIST] Starting
> [CACHE] [LIKED] Starting
> [CACHE] [ALBUM] Starting
> [CACHE] [ARTIST] Starting
> Error occurred removing key from pressed_keys
> Error occurred removing key from pressed_keys
> Error occurred removing key from pressed_keys
> Error occurred removing key from pressed_keys

**Comment by ryoburrito** [comment]
Hello, I wanted to say that I have the same problem on Mac OSX Catalina and have screen recorded the [issue](https://streamable.com/qelz86). When `ctrl + space` is pressed it will just phase out and you are unable to type anything. Using the icon in the menubar sometimes works.

**Comment by MarkMcMoran** [comment]
Okay, thanks for the feedback guys. I'll have this raised with the other contributors and arrange for testing on Catalina.

**Comment by MarkMcMoran** [comment]
Please try out this:
https://discussions.apple.com/thread/8507324

Let me know if this resolves your issue.

**Comment by ryoburrito** [comment]
Hello, this did not resolve the issue. I also tried remapping the shortcut activation to `alt + space` which has no bindings but the same issue persisted.

**Comment by MarkMcMoran** [comment]
Can you please share the stack trace received please?

**Comment by ryoburrito** [comment]
Ok, I figured out what was causing it. For some reason, when Accessibility is granted to Terminal or any IDE, the shortcut will glitch out and you are unable to type anything. Disabling Accessibility for Terminal in System Preferences > Security & Privacy > Privacy resolved the problem. Don't know why accessibility would affect it but hopefully, this helps other Mac users!

**Comment by MarkMcMoran** [comment]
I'm unfamiliar with Acccessibly in MacOS. Was there particular settings configured?
