### ISSUE TITLE
[Issue] GUI Activation

### ISSUE THREAD

**Issue by collinsinclair** [spotlightify/spotlightify#17]
Using `ctrl + space` momentarily opens GUI, but it vanishes almost immediately afterwards. In certain cases, the GUI will stay open if I use the shortcut directly after running the app, but if I change windows, etc., the shortcut fails. Usually I can open the GUI by clicking on the menu bar icon.

**Comment by CmD0** [comment]
What context is this glitch happening in? Is it in a fullscreen application? Moving to windowed borderless might fix the problem. Let us know! 🙂

**Comment by jsicherman** [comment]
Having this issue as well (Windows 10, Python 3.8.3) `Ctrl + space` will open the GUI for 0.5-1.5 seconds before it auto-closes (independent of running application). I can force it to stay open by clicking into it while it's on the screen. Same issue if I click the tray icon (haven't checked the source but it seems like the tray icon just simulates a `Ctrl + space` press).

No debug in console to pass along. Basically just seems like Windows redirects focus from the app to whatever is currently in the foreground on its next GUI update.

**Comment by MarkMcMoran** [comment]
Able to replicate issue on MacOS High Sierra version 10.13.6, using Python 3.7.7. Ctrl + space doesn't activate GUI, access from the system tray can be flaky. Actively seeking a work around for this.

**Comment by MarkMcMoran** [comment]
GUI prints out ```

**Comment by MarkMcMoran** [comment]
> CLI prints out the following when trying to press the shortcut keys:
> 
> ```
> Error occurred removing key from pressed_keys
> ```

This is linked to

**Comment by petergmurphy** [comment]
Solution: https://github.com/spotlightify/spotlightify/issues/13

**Comment by MarkMcMoran** [comment]
Hey guys, I was able to come to a resolution. PR submitted: https://github.com/spotlightify/spotlightify/pull/47, this was verified on 1280 x 800 resolution screen.

**Comment by MarkMcMoran** [comment]
@petergmurphy  this should be closed, as we concluded that click to 'focus' was not feasible, as it is not possible on Windows for security reasons.
