### ISSUE TITLE
[BUG] Can't kill process after crash

### ISSUE THREAD

**Issue by jac0b-w** [spotlightify/spotlightify#18]
OS: Windows 10

If you press the system tray icon repeatedly it becomes unresponsive. The windows 'this program is unresponsive' dialog doesn't kill the app and neither does task manager. VS Code also failed to kill. I also I tried taskkill in an elevated command prompt but I still couldn't kill the process. The only way to fix this that I know of is to restart my system.

**Comment by collinsinclair** [comment]
In macOS I have to Force Quit python in order to exit the application. Neither the `exit` command nor the Exit button form the menu bar icon successfully exit the application.

**Comment by jac0b-w** [comment]
As for fixing the exit command it's as easy as changing the `exit_app` function to `exit_app = lambda: sys.exit()`

**Comment by collinsinclair** [comment]
Brilliant - that solved it!

**Comment by jac0b-w** [comment]
It only works because it raises an exception if it's not imported. It doesn't actually work if you import sys. Just use `exit_app = lambda: raise Exception("Exit command")` instead.

**Comment by jac0b-w** [comment]
It doesn't actually work when you import sys. It only works because an exception is raised. You can use this instead
 ```
def exit_app():
    raise Exception("Exit command")
```
