### ISSUE TITLE
Test results with non-premium account

### ISSUE THREAD

**Issue by RubenNL** [spotlightify/spotlightify#23]
doesn't work. gives this error(i removed part of the device_id:

```
HTTP Error for PUT to https://api.spotify.com/v1/me/player/play?device_id=c4c852afd11255147f14f324fc30924f******** returned 403 due to Player command failed: Premium required  
[ERROR] Could not toggle playback. Make a device has been selected. Use the 'device' command to select` the appropriate device```

**Comment by MarkMcMoran** [comment]
From [`Spotify API docs`](https://developer.spotify.com/documentation/web-api/guides/using-connect-web-api/) it says the following:
"With Connect Web API you can only control Spotify Premium users’ playback."

Limitation is set by the Spotify team itself, closing ticket.
