### ISSUE TITLE
[Task] Easily configurable settings UI accessible from system tray

### ISSUE THREAD

**Issue by MarkMcMoran** [spotlightify/spotlightify#31]
To make application more user friendly, inclusion of a UI page to perform CRUD operations with client_secret, client and username values.

- [ ] UI 
- [x] Make _config.py OOP rather than hard coded values
- [x]  Somewhere to store the current hard coded values.

**Comment by MarkMcMoran** [comment]
Currently working on updating _config.py and storing the hard coded values into a json file for easy use. This file is going to be dynamically generated.

**Comment by jac0b-w** [comment]
The username isn't actually needed for authorisation. All it's used for is to name the cache file an empty string works just as well.

**Comment by jac0b-w** [comment]
Sounds good you could also get the display name from the api so that it's same as on spotify

**Comment by MarkMcMoran** [comment]
Thanks for the suggestions 😊

**Comment by MarkMcMoran** [comment]
All that is left to work on is the UI for the settings to round this issue ticket off.

**Comment by MarkMcMoran** [comment]
@petergmurphy  @wllkle  has this been achieved? If so, can this issue be closed out?

**Comment by petergmurphy** [comment]
No not yet. Right now the only configurable settings are the user credentials and that is accessed through the UI.
