### ISSUE TITLE
[Issue] Access Token Not Refreshing

### ISSUE THREAD

**Issue by petergmurphy** [spotlightify/spotlightify#48]
App fails to refresh the API user token if it has been open for longer than one hour. At the moment the app requires a restart for the token to be refreshed. This needs to be fixed. 

The function to refresh tokens can be found inside of app.py on the master branch.

**Comment by TomBPotochek** [comment]
I get the same problem. The console yields the following lines:  
```Error occurred removing key from pressed_keys
[WARNING] Could not refresh user API token
HTTP Error for GET to https://api.spotify.com/v1/me/player returned 401 due to The access token expired

**Comment by petergmurphy** [comment]
This has been fixed
