### ISSUE TITLE
Run Spotlightify

### ISSUE THREAD

**Issue by WatchTheory** [spotlightify/spotlightify#77]
This question is straight forward, I did install it and got it to run. But after turn your computer on. How do you run the application when there is not exe file. More confused than anything else.

**Comment by MarkMcMoran** [comment]
At the moment, this hasn't been configured to do this. If you'd like this to be a feature then we could convert your issue into a feature request.

**Comment by MarkMcMoran** [comment]
@petergmurphy

**Comment by WatchTheory** [comment]
That would be better if you can make it happen, it would be easier to run.

**Comment by MarkMcMoran** [comment]
you're more than welcome to put together a PR for review if you'd like

**Comment by WatchTheory** [comment]
Unfortunately, i don't know what that is or how to go about using . Just a user trying to help put any effort I can to make it better for everyone.

**Comment by petergmurphy** [comment]
Hi WatchTheory,

I'm currently working on completing the themes feature but after that it is my goal to get an executable version of Spotlightify released.

**Comment by WatchTheory** [comment]
Fantastic news. I will continue to put any feedback that i can to make Spotlightify. I love using Spotlightify, it make my life so much simpler.

**Comment by petergmurphy** [comment]
Hey there,

I'm closing this issue because Spotlightify has been completely rewritten with a new Golang backend and React Typescript frontend. The latest version is much improved—give it a try and let me know what you think!

Cheers,
Peter
