### ISSUE TITLE
Conversion of UI from PyQt to ElectronJS 

### ISSUE THREAD

**Issue by MarkMcMoran** [spotlightify/spotlightify#78]
Discussed with Peter conversion of UI to another language:

Proxy of the backend to frontend would be more feasible to get around the issue of Python's GIL locking to a single thread.

Technologies considered?

- Flask (for proxying Python to frontend)
- ElectronJS

**Comment by MarkMcMoran** [comment]
PyQt licencing is also not permissive for Open Source projects also.. 

https://riverbankcomputing.com/commercial/license-faq

**Comment by petergmurphy** [comment]
Closing this issue as Spotlightify has been rewritten using Wails, which provides a Golang backend along with a React typescript frontend.

If you're interested in getting involved with the project again Mark let me know! Just working to get a beta released for the new Spotlightify!
